name: Python Script Pipeline

on:
  push:
    branches:
      - main  # Trigger the workflow on push events to the main branch

jobs:
  run-script:
    runs-on: ubuntu-latest  # Operating system for the job

    steps:
      - name: Check out repository  # Action to check out the repository
        uses: actions/checkout@v2

      - name: Set up Python  # Action to set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Replace with your desired Python version

      - name: Run Python script  # Action to run the Python script
        run: python random_calculation2.xlsx  # Replace with your script name if different
